name: peliculas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/movie-icon.png"
  adaptive_icon_background: "assets/icon/movie-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
